[package]
name = "auriya"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
notify = "8.2.0"
toml = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", default-features = false, features = ["rt","net","sync","time","macros","io-util","signal",] }
tracing = { version = "0.1.41", default-features = false, features = ["std", "attributes"] }
tracing-subscriber = { version = "0.3.20", default-features = false, features = ["fmt","ansi","env-filter","smallvec",] }
log = "0.4.28"
android_logger = "0.15.1"
