[package]
name = "auriya"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.50", features = ["derive"] }
mpsc = "0.2.6"
notify = "8.2.0"
pair = "0.2.0"
serde = { version = "1.0.228", features = ["derive"] }
signal = "0.7.0"
time = "0.3.44"
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
