[settings]
default_governor = "schedutil"
default_enable_dnd = true

[[games]]
package = "com.mobile.legends"
cpu_governor = "performance"
enable_dnd = true

[[games]]
package = "com.supercell.clashroyale"
cpu_governor = "schedutil"
enable_dnd = false
